[colors.primary]
foreground = 0xbfbdb6
background = 0x0b0e14

[colors.cursor]
text = 0x0b0e14
cursor = 0xbfbdb6

[colors.selection]
text = 0xbfbdb6
background = 0x1b3a5b

[colors.normal]
black = 0x1e232b
red = 0xea6c73
green = 0x7fd962
yellow = 0xf9af4f
blue = 0x53bdfa
magenta = 0xcda1fa
cyan = 0x90e1c6
white = 0xc7c7c7

[colors.bright]
black = 0x686868
red = 0xf07178
green = 0xaad94c
yellow = 0xffb454
blue = 0x59c2ff
magenta = 0xd2a6ff
cyan = 0x95e6cb
white = 0xffffff
