package nu:discord-bot;

interface nu {
  resource executor {
    constructor();
    
    execute: func(
      fname: string, 
      source: string, 
      file: option<list<u8>>
    ) -> string;
  }
}

world bot {
  export nu;
}
