[package]
name = "nu-discord-bot"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
const-hex.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
serde_json.workspace = true
shuttle-axum.workspace = true
shuttle-runtime.workspace = true
static-toml.workspace = true
tokio.workspace = true
twilight-http.workspace = true
twilight-model.workspace = true
