[package]
name = "nu-discord-bot"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1"
axum = "0.8"
ed25519-dalek = "2"
const-hex = "1.14"
serde = "1"
serde_json = "1"
shuttle-axum = "0.53"
shuttle-runtime = "0.53"
tokio = "1"
twilight-http = "0.16"
twilight-model = "0.16"
static-toml = "1.3"
