package nu:discord-bot;

interface nu {
  variant file {
    text(string),
    bytes(list<u8>)
  }

  variant execute-ok {
    value(string),
    error(string),
  }

  enum execute-error {
    merge-delta,
    into-value,
    into-string,
  }

  resource executor {
    constructor();
    
    execute: func(
      fname: string, 
      source: string, 
      file: option<file>,
      cols: u16,
    ) -> result<execute-ok, execute-error>;
  }
}

world bot {
  export nu;
}
