package nu:discord-bot;

interface nu {
  variant file {
    text(string),
    bytes(list<u8>)
  }

  resource executor {
    constructor();
    
    execute: func(
      fname: string, 
      source: string, 
      file: option<file>
    ) -> string;
  }
}

world bot {
  export nu;
}
